-- ENUMS

DO $$
BEGIN
    IF NOT EXISTS (SELECT * FROM pg_type WHERE typename = 'users_role')
THEN
        CREATE TYPE users_role AS ENUM ('ADMIN', 'INSTRUCTOR', 'STUDENT');
    END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT * FROM pg_type WHERE typename = 'forum_type')
THEN
        CREATE TYPE forum_type AS ENUM ('DISCUSSION', 'QUESTION');
    END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT * FROM pg_type WHERE typename = 'general_status')
THEN
        CREATE TYPE general_status AS ENUM ('OPEN', 'CLOSED');
    END IF;
END$$;

-- ADDRESS ----------------------------------
-- TABELA EXEMPLO ----------------

CREATE TABLE IF NOT EXISTS address (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    address VARCHAR(255) NOT NULL,
    number VARCHAR(10) NOT NULL,
    complement VARCHAR(30),
    neighborhood VARCHAR(100),
    state VARCHAR(100) NOT NULL,
    cep VARCHAR(9)
);

-- exemplo associativa USER_ADDRESS -----------------------------
CREATE TABLE IF NOT EXISTS user_address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CONSTRAINT fk_user_address
            FOREIGN KEY (user_address_id)
            REFERENCES address(id),
    CONSTRAINT fk_institution_user
            FOREIGN KEY (users_id)
            REFERENCES users(id)
);