spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/forumhub
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Contexto da aplicação
server.servlet.context-path=/forum-hub/v1/api

# Outras configs úteis
server.error.include-stacktrace=never
logging.level.org.springframework.security=DEBUG